
version: "3.3"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017
  app:
    build: .
    container_name: oneassure_server
    ports:
      - 5000:5000
    depends_on:
      - mongo
    
volumes:
  mongo_data: 